version: '3.8'

services:
    db:
        image: mysql:8
        restart: no
        container_name: db
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 10s
            timeout: 5s
            retries: 5
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: laravel
        volumes:
            - dbdata:/var/lib/mysql/
        networks:
            - app-network
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: no
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ../:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ./nginx/ssl/:/etc/nginx/ssl/
        networks:
            - app-network
    app:
        build:
            args:
                user: developer
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: app
        command: >
            sh -c "composer install && php artisan key:generate && php artisan migrate && php-fpm"
        container_name: location-app
        restart: no
        environment:
            VIRTUAL_HOST: localhost
        working_dir: /var/www/
        volumes:
            - ../:/var/www
            - ~/.ssh:/root/.ssh
        depends_on:
            db:
                condition: service_healthy
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
volumes:
    dbdata:
        driver: local
